services:
  - type: web
    name: the-wedding-plan
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /backoffice/index.html
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_AUTH_ALLOWED_EMAILS
        sync: false
      - key: APP_AUTH_SUCCESS_REDIRECT_URL
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false

