spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wedding_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

app:
  cors:
    allowed-origins: []
    allowed-origin-patterns: []
    allowed-methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
    allowed-headers: [Authorization, Content-Type, Accept, Origin]
    allow-credentials: true
