server:
  servlet:
    session:
      cookie:
        secure: false

app:
  auth:
    success-redirect-url: http://localhost:5173
  guest-access:
    base-url: http://localhost:8080
    guest-area-url: http://localhost:5174/guest-access/secured-area
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:5174
    allowed-origin-patterns:
      - http://localhost:*
      - http://127.0.0.1:*
