server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: lax

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require
